services:
  postgres:
    image: 'postgres:14.1-alpine'
    environment:
      - POSTGRES_DB=monitoring_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis: # Name of container
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  app:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    command: npm run start:prod
    ports:
      - 3000:3000
    depends_on:
      - redis
      - postgres

volumes:
  postgres:
  redis:
    driver: local
